import type { ColumnAlign, ColumnKind, LookupKind } from "@/features/stocks/_shared/types";
import type { PhysicalStockListRow } from "./PhysicalStockListModal";

export type PhysicalStockColumn = {
  key: string;
  header: string;
  width: string;
  align: ColumnAlign;
  kind: ColumnKind;
  lookupKind?: LookupKind;
  options?: readonly string[];
  defaultValue?: string;
  readOnly?: boolean;
};
export type PhysicalStockRow = {
  id: number;
  values: Record<string, string>;
};
export type PhysicalStockSaveDetail = {
  psdRowNo: number;
  psdAccYear: string;
  psdCompanyId: string;
  psdBranchId: string;
  psdGodownId: string;
  psdItemId: string;
  psdUnitId: string;
  psdBaseUnitId: string;
  psdToBaseFactor: number;
  psdBarcode?: string | null;
  psdMrp?: number;
  psdTrackingType?: "NONE" | "MRP" | "BATCH" | "SERIAL";
  psdBookQty?: number;
  psdBookBaseQty?: number;
  psdPhysicalQty?: number;
  psdPhysicalBaseQty?: number;
  psdDiffQty?: number;
  psdDiffBaseQty?: number;
  psdStockRateWot?: number;
  psdStockRateWithTax?: number;
  psdReasonId?: string | null;
  psdResolution?: "ADJUST_LOSS_GAIN";
  psdNotes?: string | null;
  batchDetails?: PhysicalStockSaveBatchDetail[];
};
export type PhysicalStockSaveBatchDetail = {
  psbRowNo: number;
  psbAccYear: string;
  psbCompanyId: string;
  psbBranchId: string;
  psbGodownId: string;
  psbItemId: string;
  psbUnitId: string;
  psbBaseUnitId: string;
  psbToBaseFactor: number;
  psbBatchId?: string | null;
  psbBatchNo?: string | null;
  psbMfgBatchNo?: string | null;
  psbBatchDate?: string | null;
  psbMfgDate?: string | null;
  psbExpiryDate?: string | null;
  psbMrp?: number;
  psbBarcode?: string | null;
  psbSerialNo?: string | null;
  psbBookQty?: number;
  psbBookBaseQty?: number;
  psbPhysicalQty?: number;
  psbPhysicalBaseQty?: number;
  psbDiffQty?: number;
  psbDiffBaseQty?: number;
  psbStockRateWot?: number;
  psbStockRateWithTax?: number;
  psbReasonId?: string | null;
  psbResolution?: "ADJUST_LOSS_GAIN";
  psbNotes?: string | null;
};
export type PhysicalStockSaveRequest = {
  psId?: string;
  psAccYear: string;
  psCompanyId: string;
  psBranchId: string;
  psGodownId: string;
  psDocNo: number;
  psDocRefNo: string | null;
  psDocDate: string;
  psCountType: "FULL";
  psStockCutoffAt: string;
  psFreezeStock: boolean;
  psPostingMode: "ADJUST_DIFFERENCE_ONLY";
  psRateSource: "MANUAL";
  psTotalLines: number;
  psTotalBookValue: number;
  psTotalCountedValue: number;
  psNetVarianceValue: number;
  psStatus: "DRAFT";
  psApprovalRequired: boolean;
  psDeviceType: "WEB";
  psDeviceId: string | null;
  psCounterId: string;
  psSessionId: string | null;
  psRemarks: string | null;
  psCreatedBy: string;
  psModifiedBy?: string | null;
  details: PhysicalStockSaveDetail[];
};
export type PhysicalStockSuccessResponse<T> = {
  success: true;
  message: string;
  data: T;
  meta?: PhysicalStockListMeta;
};
export type PhysicalStockListMeta = {
  page: number;
  limit: number;
  total: number;
  total_pages: number;
};
export type PhysicalStockHeaderPayload = PhysicalStockListRow & {
  psc_acc_year?: string;
  psc_company_id?: string;
  psc_branch_id?: string;
  psc_godown_id?: string;
  psc_godown_name?: string | null;
  psc_device_type?: string | null;
  psc_device_id?: string | null;
  psc_session_id?: string | null;
  psc_remarks?: string | null;
};
export type PhysicalStockBatchDetailPayload = {
  psb_id: string;
  psb_psd_id: string;
  psb_row_no: number;
  psb_batch_id?: string | null;
  psb_batch_no?: string | null;
  psb_mfg_batch_no?: string | null;
  psb_to_base_factor?: number | null;
  psb_batch_date?: string | null;
  psb_mfg_date?: string | null;
  psb_expiry_date?: string | null;
  psb_mrp?: number | null;
  psb_barcode?: string | null;
  psb_serial_no?: string | null;
  psb_book_qty?: number | null;
  psb_book_base_qty?: number | null;
  psb_physical_qty?: number | null;
  psb_physical_base_qty?: number | null;
  psb_diff_qty?: number | null;
  psb_diff_base_qty?: number | null;
  psb_stock_rate_wot?: number | null;
  psb_stock_rate_with_tax?: number | null;
  psb_notes?: string | null;
};
export type PhysicalStockDetailPayload = {
  psd_id: string;
  psd_psc_id: string;
  psd_row_no: number;
  psd_godown_id?: string;
  psd_godown_name?: string | null;
  psd_item_id?: string;
  psd_item_code?: string | null;
  psd_item_name?: string | null;
  psd_unit_id?: string;
  psd_unit_name?: string | null;
  psd_base_unit_id?: string;
  psd_base_unit_name?: string | null;
  psd_to_base_factor?: number | null;
  psd_barcode?: string | null;
  psd_mrp?: number | null;
  psd_tracking_type?: string | null;
  psd_book_qty?: number | null;
  psd_book_base_qty?: number | null;
  psd_physical_qty?: number | null;
  psd_physical_base_qty?: number | null;
  psd_diff_qty?: number | null;
  psd_diff_base_qty?: number | null;
  psd_stock_rate_wot?: number | null;
  psd_stock_rate_with_tax?: number | null;
  psd_notes?: string | null;
  batch_details: PhysicalStockBatchDetailPayload[];
};
export type PhysicalStockDocumentResponse = {
  header: PhysicalStockHeaderPayload;
  details: PhysicalStockDetailPayload[];
};
export type ItemStockBalancePayload = {
  isb_closing_qty?: number | string | null;
  isb_free_closing_qty?: number | string | null;
  book_qty?: number | string | null;
  book_base_qty?: number | string | null;
  book_free_qty?: number | string | null;
  book_free_base_qty?: number | string | null;
};
export type ItemBatchStockLookupPayload = ItemStockBalancePayload & {
  ibs_id: string;
  ibs_batch_id: string;
  ibs_batch_no: string | null;
  ibs_mfg_batch_no?: string | null;
  ibs_batch_date?: string | null;
  ibs_mfg_date?: string | null;
  ibs_expiry_date?: string | null;
  ibs_mrp?: number | string | null;
  ibs_barcode?: string | null;
  ibs_serial_no?: string | null;
  ibs_avg_stock_rate?: number | string | null;
  ibs_avg_stock_rate_wot?: number | string | null;
};
export type ItemStockBalanceRowScope = {
  itemId: string;
  unitId: string;
  godownId: string;
};
export type RowValidationIssue = {
  rowId: number;
  fieldKey: string;
  message: string;
};
export type UiTableColumnPayload = {
  uiTblClmId?: string;
  uiTblClmNo?: string;
  uiTblClmTableId?: string | null;
  uiTblClmName: string | null;
  uiTblClmColumnWidth: number | null;
  uiTblClmColumnVisibility: boolean | null;
  uiTblClmColumnFocus?: boolean | null;
  uiTblClmColumnPosition: number | null;
  uiTblClmColumnNecessity?: boolean | null;
  uiTblClmNextColumn?: number | null;
  uiTblClmPreviousColumn?: number | null;
  uiTblClmIsActive?: boolean | null;
};
export type SavePhysicalStockUiTableColumnRequest = {
  uiTblClmId?: string;
  uiTblClmNo?: string;
  uiTblClmName: string;
  uiTblClmTableId: string | null;
  uiTblClmColumnWidth: number | null;
  uiTblClmColumnVisibility: boolean;
  uiTblClmColumnFocus: boolean;
  uiTblClmColumnPosition: number;
  uiTblClmColumnNecessity: boolean;
  uiTblClmNextColumn: number | null;
  uiTblClmPreviousColumn: number | null;
  uiTblClmIsActive: boolean;
};
export type PhysicalStockLoadRequest =
  | { type: "latest" }
  | { type: "refno"; refNo: string }
  | { type: "stock"; stockId: string; label: string };
export type PhysicalStockListFilters = {
  search: string;
  dateFrom: string;
  dateTo: string;
};
export type LoadedPhysicalStockMeta = {
  stockId: string;
  stockLabel: string;
  stockDate: string;
  stockDocNo: string | null;
  companyId: string | null;
  branchId: string | null;
};
