/**
 * Captured from the box on 2026-09-26 — `/menu-masters/get?visibleOnly=true`
 * (125 nodes under 7 roots) and one real user's `menus[]` (80 rows,
 * with the live stale grants on menus 249 and 250: CREATE / EDIT / DELETE /
 * EXPORT held on screens whose verbs are VIEW and PRINT only). The user's
 * identity below is invented; the rows are not.
 *
 * Generated — regenerate rather than hand-edit.
 */
import type { MenuTreeNodePayload, UserAdminPayload, UserMenuPayload } from "./wire";

export const LIVE_MENU_TREE_PAYLOAD: MenuTreeNodePayload[] = [
  {"menuId":1,"menuParentId":null,"menuName":"&1 Sales","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":true,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
    {"menuId":10,"menuParentId":1,"menuName":"Customers","menuAlias":"CTRL+SHIFT+C","menuVisibility":true,"menuPosition":"1.00","menuSeparator":true,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":189,"menuParentId":1,"menuName":"Optical Prescription","menuAlias":null,"menuVisibility":true,"menuPosition":"1.10","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":11,"menuParentId":1,"menuName":"Sales Order","menuAlias":"CTRL+SHIFT+S","menuVisibility":true,"menuPosition":"2.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","AMEND","OVERRIDE"],"permissions":null},
    {"menuId":12,"menuParentId":1,"menuName":"Sales Entry","menuAlias":"CTRL+S","menuVisibility":true,"menuPosition":"3.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","AMEND","OVERRIDE","RETENDER"],"permissions":null},
    {"menuId":229,"menuParentId":1,"menuName":"Sale Entry (Bulk)","menuAlias":null,"menuVisibility":true,"menuPosition":"3.10","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":13,"menuParentId":1,"menuName":"Sales Return","menuAlias":"CTRL+R","menuVisibility":true,"menuPosition":"4.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","AMEND","OVERRIDE"],"permissions":null},
    {"menuId":14,"menuParentId":1,"menuName":"Quotation","menuAlias":"CTRL+Q","menuVisibility":true,"menuPosition":"5.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","AMEND","OVERRIDE"],"permissions":null},
    {"menuId":226,"menuParentId":1,"menuName":"Bill Delivery Update","menuAlias":"true","menuVisibility":true,"menuPosition":"6.10","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":257,"menuParentId":1,"menuName":"Temp Credits","menuAlias":null,"menuVisibility":true,"menuPosition":"6.20","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":17,"menuParentId":1,"menuName":"Master","menuAlias":null,"menuVisibility":true,"menuPosition":"8.00","menuSeparator":true,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
      {"menuId":18,"menuParentId":17,"menuName":"State Master","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":19,"menuParentId":17,"menuName":"City Master","menuAlias":null,"menuVisibility":true,"menuPosition":"2.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":20,"menuParentId":17,"menuName":"Area Master","menuAlias":null,"menuVisibility":true,"menuPosition":"3.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":21,"menuParentId":17,"menuName":"Customer Type Master","menuAlias":null,"menuVisibility":true,"menuPosition":"4.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":95,"menuParentId":17,"menuName":"Tender Master","menuAlias":null,"menuVisibility":true,"menuPosition":"5.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":130,"menuParentId":17,"menuName":"Vehicle Freight Charges","menuAlias":null,"menuVisibility":true,"menuPosition":"8.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":177,"menuParentId":17,"menuName":"Loading Charges","menuAlias":null,"menuVisibility":true,"menuPosition":"8.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    ]},
    {"menuId":75,"menuParentId":1,"menuName":"Loyalty Schemes","menuAlias":null,"menuVisibility":true,"menuPosition":"10.00","menuSeparator":true,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
      {"menuId":67,"menuParentId":75,"menuName":"Loyalty Programs","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    ]},
    {"menuId":66,"menuParentId":1,"menuName":"Offer & Schemes","menuAlias":null,"menuVisibility":true,"menuPosition":"12.00","menuSeparator":true,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
      {"menuId":247,"menuParentId":66,"menuName":"Promotion Scheme","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    ]},
  ]},
  {"menuId":2,"menuParentId":null,"menuName":"&2 Purchase","menuAlias":null,"menuVisibility":true,"menuPosition":"2.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
    {"menuId":22,"menuParentId":2,"menuName":"Suppliers","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":true,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":26,"menuParentId":2,"menuName":"Master","menuAlias":null,"menuVisibility":true,"menuPosition":"5.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
      {"menuId":27,"menuParentId":26,"menuName":"Supplier Groups","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    ]},
  ]},
  {"menuId":3,"menuParentId":null,"menuName":"&3 Inventory","menuAlias":null,"menuVisibility":true,"menuPosition":"3.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
    {"menuId":29,"menuParentId":3,"menuName":"Item Master","menuAlias":"CTRL+I","menuVisibility":true,"menuPosition":"1.00","menuSeparator":true,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":34,"menuParentId":3,"menuName":"Master","menuAlias":null,"menuVisibility":true,"menuPosition":"7.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
      {"menuId":35,"menuParentId":34,"menuName":"Item Group Master","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":36,"menuParentId":34,"menuName":"Item Brand Master","menuAlias":null,"menuVisibility":true,"menuPosition":"2.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":240,"menuParentId":34,"menuName":"item category master","menuAlias":"item-category-master","menuVisibility":true,"menuPosition":"2.10","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":37,"menuParentId":34,"menuName":"Item Section Master","menuAlias":null,"menuVisibility":true,"menuPosition":"3.00","menuSeparator":true,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":38,"menuParentId":34,"menuName":"Unit Master","menuAlias":null,"menuVisibility":true,"menuPosition":"4.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":39,"menuParentId":34,"menuName":"Godown Master","menuAlias":null,"menuVisibility":true,"menuPosition":"5.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":40,"menuParentId":34,"menuName":"Tax Master","menuAlias":null,"menuVisibility":true,"menuPosition":"6.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":244,"menuParentId":34,"menuName":"Item Qty wise Price","menuAlias":null,"menuVisibility":true,"menuPosition":"7.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":249,"menuParentId":34,"menuName":"Stock Track Policy","menuAlias":null,"menuVisibility":true,"menuPosition":"8.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","PRINT"],"permissions":null},
    ]},
  ]},
  {"menuId":4,"menuParentId":null,"menuName":"&4 Stock","menuAlias":null,"menuVisibility":true,"menuPosition":"4.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
    {"menuId":44,"menuParentId":4,"menuName":"Opening Stock","menuAlias":null,"menuVisibility":true,"menuPosition":"4.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","AMEND","OVERRIDE"],"permissions":null},
    {"menuId":45,"menuParentId":4,"menuName":"Physical Stock Update","menuAlias":"CTRL+SHIFT+U","menuVisibility":true,"menuPosition":"5.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","AMEND","OVERRIDE"],"permissions":null},
  ]},
  {"menuId":5,"menuParentId":null,"menuName":"&5 Accounts","menuAlias":null,"menuVisibility":true,"menuPosition":"5.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
    {"menuId":55,"menuParentId":5,"menuName":"Opening Balance","menuAlias":null,"menuVisibility":true,"menuPosition":"0.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","AMEND","OVERRIDE"],"permissions":null},
    {"menuId":54,"menuParentId":5,"menuName":"Ledger Group Master","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":53,"menuParentId":5,"menuName":"Ledger Master","menuAlias":null,"menuVisibility":true,"menuPosition":"2.00","menuSeparator":true,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":49,"menuParentId":5,"menuName":"Bill wise Payment","menuAlias":"CTRL+SHIFT+B","menuVisibility":true,"menuPosition":"4.00","menuSeparator":true,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":99,"menuParentId":5,"menuName":"Receipt","menuAlias":null,"menuVisibility":true,"menuPosition":"6.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","AMEND","OVERRIDE"],"permissions":null},
    {"menuId":101,"menuParentId":5,"menuName":"Debit Note","menuAlias":null,"menuVisibility":true,"menuPosition":"8.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","OVERRIDE"],"permissions":null},
    {"menuId":102,"menuParentId":5,"menuName":"Credit Note","menuAlias":null,"menuVisibility":true,"menuPosition":"9.00","menuSeparator":true,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","OVERRIDE"],"permissions":null},
    {"menuId":103,"menuParentId":5,"menuName":"Journal","menuAlias":null,"menuVisibility":true,"menuPosition":"10.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","OVERRIDE"],"permissions":null},
    {"menuId":104,"menuParentId":5,"menuName":"Contra","menuAlias":null,"menuVisibility":true,"menuPosition":"11.00","menuSeparator":true,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","OVERRIDE"],"permissions":null},
    {"menuId":163,"menuParentId":5,"menuName":"Purchase (Accounting)","menuAlias":null,"menuVisibility":true,"menuPosition":"11.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","OVERRIDE"],"permissions":null},
    {"menuId":259,"menuParentId":5,"menuName":"Sales (Accounting)","menuAlias":null,"menuVisibility":true,"menuPosition":"11.10","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","OVERRIDE"],"permissions":null},
    {"menuId":260,"menuParentId":5,"menuName":"Receipt Voucher","menuAlias":null,"menuVisibility":true,"menuPosition":"11.20","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","OVERRIDE"],"permissions":null},
    {"menuId":261,"menuParentId":5,"menuName":"Payment Voucher","menuAlias":null,"menuVisibility":true,"menuPosition":"11.30","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","OVERRIDE"],"permissions":null},
    {"menuId":262,"menuParentId":5,"menuName":"Voucher Register","menuAlias":null,"menuVisibility":true,"menuPosition":"11.40","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","OVERRIDE"],"permissions":null},
    {"menuId":51,"menuParentId":5,"menuName":"Received Cheques","menuAlias":null,"menuVisibility":true,"menuPosition":"12.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","AMEND","OVERRIDE"],"permissions":null},
    {"menuId":52,"menuParentId":5,"menuName":"Issued Cheques","menuAlias":null,"menuVisibility":true,"menuPosition":"13.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT","POST","CANCEL","AMEND","OVERRIDE"],"permissions":null},
  ]},
  {"menuId":6,"menuParentId":null,"menuName":"&6 Reports","menuAlias":null,"menuVisibility":true,"menuPosition":"6.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
    {"menuId":106,"menuParentId":6,"menuName":"Audit Logs","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":137,"menuParentId":6,"menuName":"Financial Statements","menuAlias":null,"menuVisibility":true,"menuPosition":"7.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
      {"menuId":258,"menuParentId":137,"menuName":"Ledger Statement","menuAlias":null,"menuVisibility":true,"menuPosition":"0.50","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","PRINT","EXPORT"],"permissions":null},
    ]},
  ]},
  {"menuId":7,"menuParentId":null,"menuName":"&7 Settings","menuAlias":null,"menuVisibility":true,"menuPosition":"7.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
    {"menuId":56,"menuParentId":7,"menuName":"Company Master","menuAlias":null,"menuVisibility":true,"menuPosition":"0.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":191,"menuParentId":7,"menuName":"Branch Master","menuAlias":null,"menuVisibility":true,"menuPosition":"0.10","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":57,"menuParentId":7,"menuName":"Employee Master","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":241,"menuParentId":7,"menuName":"gsp company service","menuAlias":"gsp sc","menuVisibility":true,"menuPosition":"2.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":58,"menuParentId":7,"menuName":"User Administration","menuAlias":null,"menuVisibility":true,"menuPosition":"3.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":59,"menuParentId":7,"menuName":"Module Administration","menuAlias":null,"menuVisibility":true,"menuPosition":"5.00","menuSeparator":true,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    {"menuId":60,"menuParentId":7,"menuName":"Configuration","menuAlias":null,"menuVisibility":true,"menuPosition":"6.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
      {"menuId":62,"menuParentId":60,"menuName":"Printing Configuration","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":248,"menuParentId":60,"menuName":"Printing Assignments","menuAlias":null,"menuVisibility":true,"menuPosition":"1.20","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":174,"menuParentId":60,"menuName":"Price Level Configuration","menuAlias":null,"menuVisibility":true,"menuPosition":"4.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":243,"menuParentId":60,"menuName":"widget-master","menuAlias":null,"menuVisibility":true,"menuPosition":"6.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":245,"menuParentId":60,"menuName":"Charge master","menuAlias":null,"menuVisibility":true,"menuPosition":"7.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":246,"menuParentId":60,"menuName":"app settings","menuAlias":null,"menuVisibility":true,"menuPosition":"8.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":250,"menuParentId":60,"menuName":"Ledger mapping","menuAlias":null,"menuVisibility":true,"menuPosition":"8.10","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","PRINT"],"permissions":null},
    ]},
    {"menuId":159,"menuParentId":7,"menuName":"Templates","menuAlias":null,"menuVisibility":true,"menuPosition":"6.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
      {"menuId":160,"menuParentId":159,"menuName":"Customer Template","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":161,"menuParentId":159,"menuName":"Item Template","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    ]},
    {"menuId":69,"menuParentId":7,"menuName":"Masters","menuAlias":null,"menuVisibility":true,"menuPosition":"11.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null,"children":[
      {"menuId":70,"menuParentId":69,"menuName":"Department Master","menuAlias":null,"menuVisibility":true,"menuPosition":"1.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":71,"menuParentId":69,"menuName":"Designation Master","menuAlias":null,"menuVisibility":true,"menuPosition":"2.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":239,"menuParentId":69,"menuName":"device list master","menuAlias":"device-listmaster","menuVisibility":true,"menuPosition":"4.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":77,"menuParentId":69,"menuName":"Dropdown Settings","menuAlias":null,"menuVisibility":true,"menuPosition":"7.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":73,"menuParentId":69,"menuName":"Grid Settings","menuAlias":null,"menuVisibility":true,"menuPosition":"8.00","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
      {"menuId":242,"menuParentId":69,"menuName":"ui- table-master","menuAlias":null,"menuVisibility":true,"menuPosition":"8.10","menuSeparator":false,"menuIsActive":true,"menuVerbs":["VIEW","CREATE","EDIT","DELETE","PRINT","EXPORT"],"permissions":null},
    ]},
  ]},
];

export const LIVE_USER_MENUS: UserMenuPayload[] = [
  {"umMenuId":1,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":2,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":3,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":4,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":5,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":6,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":7,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":10,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":11,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":true,"umCanOverride":true,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":12,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":true,"umCanOverride":true,"umCanRetender":true,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":13,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":true,"umCanOverride":true,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":14,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":17,"umCanView":false,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":18,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":19,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":false,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":20,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":21,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":22,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":26,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":27,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":29,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":34,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":35,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":36,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":37,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":38,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":39,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":40,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":44,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":45,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":49,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":51,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":true,"umCanOverride":true,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":53,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":54,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":55,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":true,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":56,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":57,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":58,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":59,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":60,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":62,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":66,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":67,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":69,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":70,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":71,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":73,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":75,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":77,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":95,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":99,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":true,"umCanOverride":true,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":101,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":false,"umCanOverride":true,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":102,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":false,"umCanOverride":true,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":103,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":false,"umCanOverride":true,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":104,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":false,"umCanOverride":true,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":106,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":130,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":159,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":160,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":161,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":163,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":false,"umCanOverride":true,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":174,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":177,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":191,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":239,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":240,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":241,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":242,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":243,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":244,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":245,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":246,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":247,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":248,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":249,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":250,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":false,"umCanCancel":false,"umCanAmend":false,"umCanOverride":false,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":259,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":false,"umCanOverride":true,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":260,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":false,"umCanOverride":true,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":261,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":false,"umCanOverride":true,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
  {"umMenuId":262,"umCanView":true,"umCanCreate":true,"umCanEdit":true,"umCanDelete":true,"umCanPrint":true,"umCanExport":true,"umCanPost":true,"umCanCancel":true,"umCanAmend":false,"umCanOverride":true,"umCanRetender":false,"umVisibility":true,"umIsFavourite":false,"umIsPinned":false,"umSortOrder":0},
];

export const LIVE_USER_ID = "019e441b-6e48-7918-b246-b857ffb35db1";

/** The GET payload for that user — every key `UserAdminPayloadDto` declares. */
export function liveUserPayload(overrides: Partial<UserAdminPayload> = {}): UserAdminPayload {
  return {
    usrId: LIVE_USER_ID,
    usrCompanyId: "019e43d9-0000-7000-8000-000000000c01",
    usrCompanyName: "Zenith Traders",
    usrBranchId: "019e43d9-0000-7000-8000-000000000b01",
    usrBranchName: "Head Office",
    usrEmployeeId: null,
    usrLoginName: "arjun",
    usrDisplayName: "Arjun",
    usrFullName: "Arjun Kumar",
    usrMobileNo: "9876543210",
    usrEmail: "arjun@example.com",
    usrAvatarUrl: null,
    usrTimezone: "UTC",
    usrLanguage: "en",
    usrMustChangePassword: false,
    usrPasswordExpiresOn: null,
    usrPasswordChangedOn: "2026-09-01T10:00:00.000Z",
    usrType: "USER",
    usrEditDate: false,
    usrEditEntry: true,
    usrEditRate: false,
    usrDesktopLogin: true,
    usrWebLogin: true,
    usrMobileLogin: false,
    usrIsActive: true,
    usrIsLocked: false,
    usrFailedLoginCount: 0,
    usrLastFailedLoginOn: null,
    usrLockedOn: null,
    usrLockedBy: null,
    usrLastLoginOn: "2026-09-25T04:12:00.000Z",
    usrIsDeleted: false,
    usrNotes: null,
    usrSyncDate: null,
    usrCreatedOn: "2026-05-20T09:30:00.000Z",
    usrCreatedBy: null,
    usrModifiedOn: null,
    usrModifiedBy: null,
    menus: LIVE_USER_MENUS.map((row) => ({ ...row })),
    ...overrides,
  };
}
